SET SERVEROUTPUT ON;
DECLARE
    S EMP.SAL%TYPE;
BEGIN
    SELECT SAL INTO S FROM EMP WHERE EMPNO=7788;
    IF S<35000 THEN
        UPDATE EMP SET SAL=35000 WHERE EMPNO=7788;
    END IF;
END;
/
SELECT * FROM EMP;
CREATE TABLE TEMP_EMP AS SELECT * FROM EMP WHERE 1=2;
SET SERVEROUTPUT ON;
DECLARE
    NEWREC EMP%ROWTYPE;
BEGIN
    SELECT * INTO NEWREC FROM EMP WHERE EMPNO=7698;
    INSERT INTO TEMP_EMP VALUES(NEWREC.EMPNO,NEWREC.ENAME,NEWREC.JOB,NEWREC.MGR,NEWREC.HIREDATE,NEWREC.SAL,NEWREC.COMM,NEWREC.DEPTNO);
END;
/
SELECT * FROM TEMP_EMP;
DROP TABLE TEMP_EMP;
SET SERVEROUTPUT ON;
DECLARE 
    A VARCHAR(10);
BEGIN
    A :='&A';
    dbms_output.put_line('HELLO '||A);
END;
/
SET SERVEROUTPUT ON;
DECLARE 
    B NUMBER(2);
BEGIN
    FOR B IN 1..5 
    LOOP
        dbms_output.put_line('VALUES '||B);
    END LOOP;
END;
/
SET SERVEROUTPUT ON;
DECLARE
    NEWCOMM EMP.COMM%TYPE;
BEGIN
    SELECT COMM INTO NEWCOMM FROM EMP WHERE EMPNO=7369;
    IF NEWCOMM IS NULL THEN
        UPDATE EMP SET COMM=3500 WHERE EMPNO=7369;
    ELSE
        NEWCOMM:=NEWCOMM*1.25;
        UPDATE EMP SET COMM=NEWCOMM WHERE EMPNO=7369;
    END IF;
END;
/
SET SERVEROUTPUT ON;
DECLARE
    C NUMBER(2);
    MO NUMBER(2);
BEGIN
    FOR C IN 1..10 
    LOOP
        MO := MOD(C,2);
        IF MO=0 THEN
            dbms_output.put_line('EVEN NUMBER:-'||C);
        END IF;
    END LOOP;
END;
/
SET SERVEROUTPUT ON;
DECLARE 
    DA NUMBER(4);
    SA EMP.SAL%TYPE;
    EMP_NO EMP.EMPNO%TYPE;
BEGIN
    EMP_NO:=&EMP_NO;
    SELECT MONTHS_BETWEEN(SYSDATE,HIREDATE) INTO DA FROM EMP WHERE EMPNO=EMP_NO;
    IF(DA>12*22)THEN
        UPDATE EMP SET SAL=SAL*1.05 WHERE EMPNO=EMP_NO;
    END IF;
END;
/
SELECT * FROM EMP;