DROP TABLE  emp_new;
DROP TABLE dept_new;
CREATE TABLE emp_new AS SELECT * FROM EMP;
CREATE TABLE dept_new AS SELECT * FROM DEPT;
ALTER TABLE dept_new ADD CONSTRAINT dept_noPri PRIMARY KEY(DEPTNO);
ALTER TABLE emp_new ADD Grade CHAR(1);
ALTER TABLE emp_new ADD CONSTRAINT emp_noPri PRIMARY KEY(EMPNO);
ALTER TABLE emp_new MODIFY DEPTNO REFERENCES dept_new(DEPTNO);
UPDATE emp_new SET SAL=SAL WHERE(SAL>2500);
ALTER TABLE emp_new MODIFY(SAL NUMBER(10,2) NOT NULL);
ALTER TABLE emp_new MODIFY(ENAME VARCHAR2(35));
ALTER TABLE emp_new DROP PRIMARY KEY;
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'EMP_NEW';
ALTER TABLE emp_new DROP CONSTRAINT SYS_C008235;
ALTER TABLE dept_new DISABLE CONSTRAINT dept_noPri;
ALTER TABLE dept_new drop PRIMARY key cascade;

CREATE TABLE EMP_NEW1 AS SELECT * FROM EMP;
CREATE TABLE DEPT_NEW1 AS SELECT * FROM DEPT;
ALTER TABLE DEPT_NEW1 ADD PRIMARY KEY(DEPTNO);
ALTER TABLE EMP_NEW1 MODIFY DEPTNO REFERENCES DEPT_NEW1(DEPTNO);
DROP TABLE DEPT_NEW1;

