CREATE OR REPLACE view D_10EMP AS SELECT * FROM Emp WHERE DEPTNO=20;
SELECT * FROM D_10EMP;

CREATE OR REPLACE VIEW Dept_Summary AS SELECT D.DNAME DUPU,MAX(E.SAL) MAXI,AVG(E.SAL) AVGM,MIN(E.SAL) MINI FROM EMP E,DEPT D WHERE D.DEPTNO=E.DEPTNO group BY D.DNAME;
SELECT * FROM Dept_Summary;

CREATE OR REPLACE VIEW Emp_Data AS SELECT * FROM EMP WHERE SAL>=20000 AND SAL<=10000 AND MGR IN (SELECT DISTINCT(EMPNO) FROM EMP) AND DEPTNO IN (SELECT DEPTNO FROM DEPT) WITH CHECK OPTION;
SELECT * FROM Emp_Data;

SQL> CREATE OR REPLACE VIEW TIME_ACCESS AS SELECT * FROM EMP WHERE ENAME='&USER' AND TO_CHAR(SYSDATE,'hh24') BETWEEN 9 AND 24 AND TO_CHAR(SYSDATE,'d') BETWEEN 2 AND 7 WITH CHECK OPTION;
SELECT * FROM TIME_ACCESS;

CREATE OR REPLACE VIEW READ_ONLY AS SELECT JOB,MIN(SAL) MIN_SAL,MAX(SAL) MAX_SAL FROM EMP GROUP BY JOB WITH READ ONLY;
SELECT * FROM READ_ONLY;

DESC USER_VIEWS;