SET SERVEROUTPUT ON;
DECLARE
    EMPREC EMP%ROWTYPE;
    CURSOR C1 IS SELECT * FROM EMP WHERE SAL+NVL(COMM,0)>25000;
BEGIN
    FOR EMPREC IN C1
    LOOP
        dbms_output.put_line(EMPREC.EMPNO||' '||EMPREC.ENAME);
    END LOOP;
END;
/
CREATE TABLE TEMP(
    EMPNUMBER NUMBER(10),
    NAME VARCHAR(10),
    SALARY NUMBER(10)
);
SET SERVEROUTPUT ON;
DECLARE
    CURSOR C1 IS SELECT * FROM EMP ORDER BY SAL DESC;
    LU EMP%ROWTYPE;
BEGIN
    FOR LU IN C1
    LOOP
        INSERT INTO TEMP VALUES(LU.EMPNO,LU.ENAME,LU.SAL);
        EXIT WHEN C1%ROWCOUNT=5;
    END LOOP;
    COMMIT;
END;
/

DROP TABLE TEMP;
DROP TABLE EMP_SAL_INC;
CREATE TABLE EMP_SAL_INC(
    EMP_ID NUMBER(10),
    CUR_SAL NUMBER(10,2),
    INC_DATE DATE
);
SET SERVEROUTPUT ON;
DECLARE
    S NUMBER(10,2);
    EMP_SAL_REC EMP%ROWTYPE;
    CURSOR C1 IS SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME LIKE 'RESEARCH');
BEGIN
    FOR EMP_SAL_REC IN C1
    LOOP 
        S:=EMP_SAL_REC.SAL*1.02;
        INSERT INTO EMP_SAL_INC VALUES (EMP_SAL_REC.EMPNO,S,SYSDATE);
    END LOOP;
    COMMIT;
END;
/

SET SERVEROUTPUT ON;
DECLARE 
    A NUMBER(10);
BEGIN
    A:=&A;
    UPDATE DEPT SET LOC='KOLKATA' WHERE DEPTNO=A;
    IF(SQL%FOUND)
    THEN
        dbms_output.put_line('UPDATED');
    ELSE
        dbms_output.put_line('CAN NOT FOUND THE LOCATION');
    END IF;
END;
/

SET SERVEROUTPUT ON;
DECLARE
    USER_ERROR EXCEPTION;
    PRAGMA EXCEPTION_INIT(USER_ERROR,-01400);
BEGIN
    INSERT INTO EMP VALUES(NULL,'ARNAB','SCIENTIST',7380,'19-JAN-23',5000,200,30);
    EXCEPTION
    WHEN USER_ERROR THEN
        dbms_output.put_line('can not insert null value');
END;
/